### ISSUE TITLE
Homepage/Work: 標題修正

### ISSUE THREAD

**Issue by arien1014** [PowerCreationD/Kohaku#10]
泡菜專案標題改變：「日本高級超市 韭菜泡菜包裝設計」
MM 專案標題改變： 「 機電整合開發｜農用自走車控制平台 」
Vegibus 專案標題改變：「產銷系統設計｜日本農產電商物流系統」

**Comment by Arthur118** [comment]
MM 專案標題我這邊會改為：機電整合開發｜自主移動機器人控制平台

**Comment by albert9052** [comment]
好的我這邊也一起改

**Comment by Arthur118** [comment]
Work 頁面這邊已全面改好推上去了

**Comment by PowerCreationD** [comment]
我這邊也改完了，那我就將這個 issue close 了
