### ISSUE TITLE
Homepage: solution內部區域的間距

### ISSUE THREAD

**Issue by jozie-wang** [PowerCreationD/Kohaku#13]
上下間距可以固定，不然縮小後視覺效果變得很擠

寬螢幕：
![Screen Shot 2023-06-09 at 1 27 24 PM](https://github.com/PowerCreationD/Kohaku/assets/88646938/aba55c7f-9a53-4904-880a-45f487064b0c)
窄螢幕：
![Screen Shot 2023-06-09 at 1 27 38 PM](https://github.com/PowerCreationD/Kohaku/assets/88646938/26bb40a9-cc7e-44ce-b04e-d09aa19e2da5)

**Comment by albert9052** [comment]
@jozie-wang 
我個人覺得固定的話，也有點太寬了一點（？
但如果這樣改動覺得沒問題，那我也沒問題～
（請忽略上方的選項 button 顯示方式不一樣的問題）
（在 Chrome 114 以後才有提供 text-wrap: balance ，但我的電腦目前還沒更新）
![Screenshot 2023-06-12 19 05 32](https://github.com/PowerCreationD/Kohaku/assets/35403151/1734db80-d6f6-44d7-aef8-b3cb5bb8dff8)

**Comment by jozie-wang** [comment]
@albert9052
嗯...這樣好像真的有點太寬了

@arien1014 
或是如果采蘋覺得原本的就可那可以跳過這個問題～
