### ISSUE TITLE
Design Guideline: 文字反白樣式

### ISSUE THREAD

**Issue by jozie-wang** [PowerCreationD/Kohaku#14]
沒有設定到文字反白樣式
<img width="471" alt="Screen Shot 2023-06-09 at 1 44 46 PM" src="https://github.com/PowerCreationD/Kohaku/assets/88646938/10f4a07d-78a0-4cdd-9301-61c06ef5bc36">

**Comment by arien1014** [comment]
@albert9052 
🍎done!

**Comment by albert9052** [comment]
@arien1014  @jozie-wang  @Arthur118 
我查不太到圖片反白要怎麼做，各位有想法嗎？如果沒有的話，我就會只做 text 的反白喔？

**Comment by jozie-wang** [comment]
done
