### ISSUE TITLE
Homepage: Work文案文字溢出設定

### ISSUE THREAD

**Issue by jozie-wang** [PowerCreationD/Kohaku#15]
1. 目前部分頁面文字即便完整顯示，還是會出現...符號
2. 這部分隱藏過長的文字不確定會不會不好，或是設計可以斟酌調整版面？
![Screen Shot 2023-06-09 at 1 51 13 PM](https://github.com/PowerCreationD/Kohaku/assets/88646938/b30159f4-6419-4d7d-bdc4-862441ae459b)

**Comment by albert9052** [comment]
把第二段刪掉即可（MM、鳳梨同）
