### ISSUE TITLE
Homepage: Contact us區塊高度

### ISSUE THREAD

**Issue by jozie-wang** [PowerCreationD/Kohaku#17]
目前的做法是該區塊的高度會隨著螢幕縮放而縮小（因為圖片等比例縮小的原因）
但縮小到較窄的螢幕寬度時，文字會不會太過壅擠

寬螢幕：
![Screen Shot 2023-06-09 at 1 58 47 PM](https://github.com/PowerCreationD/Kohaku/assets/88646938/431403db-726c-42dc-8801-50fe8d7a53ea)

窄螢幕：
![Screen Shot 2023-06-09 at 2 00 54 PM](https://github.com/PowerCreationD/Kohaku/assets/88646938/d3fb3088-0586-46d0-b4d8-bfab93da0897)

**Comment by arien1014** [comment]
@albert9052 
螢幕寬942以下時，字體切換為手機版字體
![messageImage_1688549460118](https://github.com/PowerCreationD/Kohaku/assets/48413041/9138aefc-14bb-46a2-b0d1-2ce177f68154)

@Arthur118 
換成上面設定之後，service的字會沒辦法被一起設定到，看起來是沒有套書彥的字體🥹
<img width="1920" alt="截圖 2023-07-05 下午5 30 50" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/d59237b3-4e91-4ec3-bc39-450e60dfeb6c">

**Comment by albert9052** [comment]
@arien1014 
這個 issue 的解法還需要在星期五被討論，因為這一改動與目前的架構有一點衝突。

**Comment by jozie-wang** [comment]
closed
