### ISSUE TITLE
Work: 允許類別的複選

### ISSUE THREAD

**Issue by jozie-wang** [PowerCreationD/Kohaku#18]
* 目前為單選的篩選，但考慮到一個專案會橫跨多個類別，是否修改為可複選的選項
* 目前手機版的選單設計可能會比較難辦到這件事
* 可考慮一併在Detail頁面加入類別的標籤

電腦版：
![Screen Shot 2023-06-09 at 2 03 40 PM](https://github.com/PowerCreationD/Kohaku/assets/88646938/d2206a79-092b-4d5b-8736-ae09e1666d1b)

手機版：
![Screen Shot 2023-06-09 at 2 03 57 PM](https://github.com/PowerCreationD/Kohaku/assets/88646938/eb52dc57-90b2-4b25-bb39-380fda9644eb)

**Comment by arien1014** [comment]
@Arthur118 
電腦版UI維持原樣但可複選
手機版UI
1. 下拉選單「已選擇選項」➡️加勾勾
2. 已選擇選項顯示在下方，可按X取消
<img width="491" alt="截圖 2023-07-04 下午5 25 44" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/7773d4e5-233b-4de0-87bf-b45b2efb3680">

**Comment by arien1014** [comment]
@albert9052 @Arthur118 
顏色有新增Light gold
<img width="485" alt="截圖 2023-07-04 下午5 29 41" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/9ab7fe70-db07-4678-9d3e-c0be737bca9a">

**Comment by jozie-wang** [comment]
done
