### ISSUE TITLE
Homepage: 修改「三大語言」「五大領域」在平板時的呈現

### ISSUE THREAD

**Issue by arien1014** [PowerCreationD/Kohaku#2]
修改「三大語言」「五大領域」在平板時的呈現
目前會卡到很多字和按鈕
<img width="770" alt="截圖 2023-06-08 下午5 37 09" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/d0f0cbcb-2372-4b07-b809-a5f3cdc5fe9c">

**Comment by albert9052** [comment]
我看情況刪
