### ISSUE TITLE
Homepage: work「查看所有專案」修改

### ISSUE THREAD

**Issue by arien1014** [PowerCreationD/Kohaku#22]
work「查看所有專案」改成「查看此專案」，並導向該作品頁面
<img width="893" alt="截圖 2023-06-09 下午4 08 49" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/eea3ea90-09e8-4c30-b860-b312137c6651">
<img width="451" alt="截圖 2023-06-09 下午4 11 05" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/ccb61c44-234b-4877-b993-ef8f5d29cd08">

**Comment by jozie-wang** [comment]
closed
