### ISSUE TITLE
Homepage: 「廣島Fresta與SOGO超市攤位設計」還有需要留嗎？

### ISSUE THREAD

**Issue by albert9052** [PowerCreationD/Kohaku#24]
在 home 其實是有這頁的，但因為什麼內容都沒有，所以它的內容與照片是沿用「廣島三原車站空間設計」的。想知道還是否會補充文案和圖片，不會的話這個需要移除。

**Comment by arien1014** [comment]
@albert9052 
先不留了，照片文案集不齊，可以刪掉然後close，謝謝書彥🥹
