### ISSUE TITLE
Home: CONCEPT 大膽的概念下的文字敘述目前的斷行修正建議

### ISSUE THREAD

**Issue by Arthur118** [PowerCreationD/Kohaku#27]
目前呈現：

![Screen Shot 2023-06-12 at 2 01 55 PM](https://github.com/PowerCreationD/Kohaku/assets/53463236/fac3d079-cb0c-4784-a0d8-6fa27ed91195)

建議呈現：
![Screen Shot 2023-06-12 at 2 09 09 PM](https://github.com/PowerCreationD/Kohaku/assets/53463236/1f4cfe45-02d4-4f2a-8cce-963bfb1c25b6)

**Comment by albert9052** [comment]
@arien1014  @Arthur118 
這部分我是因為采蘋 figma 那邊也是有折起來的，因此我還特別調成有折起來（？
可能要看采蘋是否有想要不折起來（？

**Comment by arien1014** [comment]
@albert9052 @Arthur118 
我覺得可以不折起來，那時候是怕會卡到旁邊的圖所以才有折，感謝兩位🥹

**Comment by Arthur118** [comment]
@albert9052 嗯嗯我了解你是對采蘋figma的版，我覺得這邊可能是有從文案端貼上時 missed 掉的地方．詳情可以參考逸青的文案斷句：https://www.notion.so/HP_Research-c6333c363f894fedb496c0416b0941ec
@arien1014 再麻煩采蘋確認了

**Comment by Arthur118** [comment]
@arien1014 這樣我了解了，我的顧慮是文字表達上這樣的斷句呈現不太好．
