### ISSUE TITLE
Work: 平板的排版

### ISSUE THREAD

**Issue by jozie-wang** [PowerCreationD/Kohaku#28]
1. 螢幕尺寸在834時排版錯誤（如下圖）
2. 平板的排版只有在834~767，感覺涵蓋範圍可以廣一點

![powercreationd github io_Kohaku_work (1)](https://github.com/PowerCreationD/Kohaku/assets/88646938/0337b6f6-66b7-4805-8fb7-f6bdc8688d6c)

**Comment by Arthur118** [comment]
@arien1014 采蘋這邊對於平板排版的涵蓋範圍，有指定想要在哪個區間嗎？

**Comment by arien1014** [comment]
@Arthur118 
沒有特別指定可以看柏維～

然後我回去海巡發現平板的我沒做到篩選我好抱歉🥹已補上如圖！
<img width="332" alt="截圖 2023-06-12 下午7 09 10" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/23bad50b-94e6-44ff-bfbc-81157dbec62a">

**Comment by Arthur118** [comment]
@arien1014 收到，謝謝采蘋！

**Comment by Arthur118** [comment]
### 6/14 上線 Work 頁面響應
Work Filter 的響應規則：
* width >= 1267px：pill buttons
* width < 1267px：dropdown selector

Work 圖片牆的響應規則：

* width >= 1024px：維持 3234 排版規則

<img width="1188" alt="Screen Shot 2023-06-13 at 3 49 27 PM" src="https://github.com/PowerCreationD/Kohaku/assets/53463236/3ded285c-0e25-4cc0-a350-b4512f41fd96">

* 767px < width < 1024px：維持雙排排版規則

<img width="862" alt="Screen Shot 2023-06-13 at 3 49 02 PM" src="https://github.com/PowerCreationD/Kohaku/assets/53463236/5e85d269-1248-41fb-9ffb-c558e8bf21fa">

* width <= 767px：維持單排排版規則

<img width="455" alt="Screen Shot 2023-06-13 at 3 51 06 PM" src="https://github.com/PowerCreationD/Kohaku/assets/53463236/7fd3fdf9-c839-4cc3-83c9-6fde6224fd33">
