### ISSUE TITLE
Homepage: work區域點擊「企劃發想與數位行銷」會err

### ISSUE THREAD

**Issue by arien1014** [PowerCreationD/Kohaku#3]
在work區域點擊「企劃發想與數位行銷」會出現附圖err且無法返回
<img width="1464" alt="截圖 2023-06-08 下午5 41 23" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/2a279242-31d9-4767-9cb3-d734d43054f9">

且手機版default會是企劃，但下面的圖是系統設計的圖
<img width="449" alt="截圖 2023-06-08 下午6 00 20" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/383b62d5-5a1f-48ee-a6e0-e622bcc373e9">

**Comment by albert9052** [comment]
@arien1014 
「企劃發想與數位行銷」會有 error 是因為它沒有東西，我以為之後會有東西，所以才沒特別處理。想知道在沒東西的情況下，采蘋想要我怎麼呈現？

**Comment by arien1014** [comment]
今天就會有資料ㄌ！

**Comment by Arthur118** [comment]
@albert9052 采倫那邊資料有給出來了，我 Work 跟 Services 這邊內容已更新．
