### ISSUE TITLE
Homepage: 在 iPhone 的 Safari 上 Homepage 有 link 換行顯示問題

### ISSUE THREAD

**Issue by albert9052** [PowerCreationD/Kohaku#30]
![screenshot_from_Hanna](https://github.com/PowerCreationD/Kohaku/assets/35403151/8891de20-4006-4aa7-8cab-50f01a74c260)

**Comment by albert9052** [comment]
@arien1014 @Arthur118 @jozie-wang 
能幫我試試這個問題，看他有沒有被解決嗎？
我手邊沒有 iOS 裝置，我現在在認真在考慮要不要去買一台二手的 🥲

**Comment by jozie-wang** [comment]
@albert9052 13min沒問題！
