### ISSUE TITLE
Homepage: 手機版背景圖片畫質太低

### ISSUE THREAD

**Issue by jozie-wang** [PowerCreationD/Kohaku#31]
手機版的Banner、Research、Concetpt三張背景圖畫質太低了
線看起來會變成鋸齒的
![IMG_9778](https://github.com/PowerCreationD/Kohaku/assets/88646938/c5f506e2-e036-4264-be49-ac3cfe6b0c0d)
![IMG_9779](https://github.com/PowerCreationD/Kohaku/assets/88646938/179fce12-38b2-4f3f-a7a2-047350d15677)

**Comment by albert9052** [comment]
@jozie-wang 
麻煩幫我看一下我現在改的可不可以～
感謝～～～～～

**Comment by jozie-wang** [comment]
@albert9052
這樣可可！感謝！
