### ISSUE TITLE
Services: 查看更多的連結在手機版文字換行

### ISSUE THREAD

**Issue by Arthur118** [PowerCreationD/Kohaku#32]
![IMG_2003](https://github.com/PowerCreationD/Kohaku/assets/53463236/449443fc-368f-4916-9334-4ff148be0fd4)

**Comment by albert9052** [comment]
此問題如果柏維是用我的 link scss 的話，我也有遇到相同的問題，因此可能可以由我來解決就好（？

**Comment by Arthur118** [comment]
@albert9052 好的麻煩書彥了，我剛剛測試發現我其實還沒有解決這項問題．

**Comment by albert9052** [comment]
Duplicate of #30

**Comment by albert9052** [comment]
Duplicate of #30
