### ISSUE TITLE
Homepage：使用平板測試底部 Contact Us 區域跑版

### ISSUE THREAD

**Issue by Arthur118** [PowerCreationD/Kohaku#34]
測試裝置：iPad Pro 12.9 吋

![IMG_0008](https://github.com/PowerCreationD/Kohaku/assets/53463236/0fce4ed6-5290-44fa-be96-e2532e7476da)

**Comment by albert9052** [comment]
@Arthur118 
麻煩幫我測試一下還有沒有問題🥲
大感謝
