### ISSUE TITLE
Homepage：網頁版Solution頁籤內容高度不一致

### ISSUE THREAD

**Issue by ivy31220** [PowerCreationD/Kohaku#39]
前兩個頁籤(系統開發、貿易服務)點擊切換時，會發現Slogan與內文高度與後三個頁籤不一致(產品、品牌視覺、企劃這三項點擊切換時位置是相同的OK!)

![image](https://github.com/PowerCreationD/Kohaku/assets/131139631/3c670d5b-77a7-4829-ba5a-6394b4fffde6)

**Comment by albert9052** [comment]
@ivy31220 ( @arien1014 )
這是因為整塊 slogan 、內文和細項是在那個區塊置中的，我覺得看采蘋的想法

**Comment by arien1014** [comment]
@albert9052 (@ivy31220 )
我覺得可以我統一調整之後再給你～

**Comment by arien1014** [comment]
@albert9052 
改成統一slogan上方留白24px！

**Comment by albert9052** [comment]
@arien1014 
那手機版的部分呢？

**Comment by arien1014** [comment]
@albert9052 
手機版目前好像是等高的不用特別改

**Comment by jozie-wang** [comment]
closed
