### ISSUE TITLE
Homepage: work「系統設計、開發與維運」圖片更換

### ISSUE THREAD

**Issue by arien1014** [PowerCreationD/Kohaku#4]
work部分更換vegibus與mm圖片

**Comment by arien1014** [comment]
@albert9052 
換成這兩張🥹
<img width="600" alt="截圖 2023-06-09 下午5 13 03" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/b3bd32d9-feec-4d6c-b0e9-23d8efad7b1a">
<img width="719" alt="截圖 2023-06-09 下午5 13 22" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/563f9a07-c3f6-4062-aba1-76f49d2ca544">

**Comment by albert9052** [comment]
@arien1014 
已換。不過針對圖片目前的呈現效果，想請問采蘋是否有想要更改？
目前的圖片是有點像會放大填滿，因此就會是填滿整個範圍，但兩邊被切掉。
想知道采蘋有想要調整成圖片是縮小至能整張呈現，但會有上下白邊的情況（白邊想要的話可以換顏色，但如果每張都是不一樣顏色的白邊會有點麻煩）
以上想聽聽采蘋的想法，因此先不 close 。如果覺得沒問題可以直接 close 掉～

**Comment by arien1014** [comment]
@albert9052 
想改vegibus！我覺得是給你們的資料需要考慮到首頁的work🥲
我新增了要改的vegibus圖放在雲端了，可以從以下網址連過去
https://drive.google.com/file/d/1JQ_iaA-GdkDvfGC6pm2DsBvGxtiRo0y4/view?usp=sharing
