### ISSUE TITLE
Homepage：Solution標題對應

### ISSUE THREAD

**Issue by ivy31220** [PowerCreationD/Kohaku#40]
為回應【RESEARCH 大量的研究】、【CONCEPT  大膽的概念】，Solution先捨棄小字Slogan改為【SOLUTION   大格局的解方】應該會比較一致。

這個版本若不再更動字也可暫不處理此問題！

![image](https://github.com/PowerCreationD/Kohaku/assets/131139631/815626aa-b00d-4958-a3d7-8dca86b567f5)

**Comment by albert9052** [comment]
@jozie-wang ( @arien1014 )
看趯瑾與采蘋的想法～

**Comment by arien1014** [comment]
@albert9052 @jozie-wang 
我都可以～

**Comment by jozie-wang** [comment]
@albert9052 @arien1014 
我覺得統一文字可能會比較好
但考慮到soultion區塊的文字比較多，以及原本底下就有各項目的小標題了
可能要看看這樣畫面會不會太壅擠~

**Comment by arien1014** [comment]
@albert9052 @jozie-wang 
我改ㄌ讚
