### ISSUE TITLE
Contact: 防呆機制跟提示訊息

### ISSUE THREAD

**Issue by brookechiang** [PowerCreationD/Kohaku#42]
「預算」、「專案內容概述」希望也可以像「預估專案時間」，有灰灰字，提示我該怎麼寫。
「預算」多少～多少，或不給範圍，但備註台幣
❓目前如果我只寫個位數也可以過
「專案內容概述」多少字/字數不限，建議提到專案目標、初步概念、參考案例
—————————————
「公司/品牌名稱」我沒有，我是個人的話怎麼辦；
「連絡信箱」、「連絡電話」可以擇一嗎？如果我不會看信箱或是希望直接電話聯絡；
「連絡電話」沒有防呆機制，輸入錯的話可以過
（以上項目可以提供灰字提示訊息寫沒有的話怎麼辦）
—————————————
寄送出表單後跳回最後可以送出表單的頁面，讓我會停不下來想一直寄（？？），建議可以跳回首頁或是WORK！

**Comment by arien1014** [comment]
@jozie-wang 
新增「預算」、「專案內容概述」、「公司/品牌名稱」灰字
<img width="491" alt="截圖 2023-07-04 下午5 39 33" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/1013aef9-9dce-42ad-a05a-93c2ededf6d8">
<img width="480" alt="截圖 2023-07-04 下午5 39 38" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/27858f43-dabf-41ac-b651-52d16dac4d48">

**Comment by jozie-wang** [comment]
done
