### ISSUE TITLE
Service : 代表作品調整建議

### ISSUE THREAD

**Issue by brookechiang** [PowerCreationD/Kohaku#44]
「品牌形象與視覺設計」點進去的頁頭關鍵字便看到「一頁書」，但代表性作品、WORKS，書都不見了，建議名片可以擇一改放工具書

**Comment by brookechiang** [comment]
<img width="978" alt="截圖 2023-06-14 下午1 21 39" src="https://github.com/PowerCreationD/Kohaku/assets/111740253/00e879cb-6709-401f-8da7-72a8558200f0">

**Comment by arien1014** [comment]
@Arthur118 
視覺設計圖片更改
<img width="663" alt="截圖 2023-07-04 下午5 43 04" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/5adcf0bb-e0cb-4eef-87ad-a5af28fd3867">
