### ISSUE TITLE
Homepage: 照片影響載入時間、照片前後不一致

### ISSUE THREAD

**Issue by brookechiang** [PowerCreationD/Kohaku#45]
第一次開首頁WORK覽表時，左右切換圖片換得比較慢，也沒有緩衝的動畫，所以心中冒出疑問「是沒有、還是當機？」
具體發生：「系統設計、開發與維運」的Vegibus、MM之間的切換

從WORK覽表轉到查看所有專案時，MM是唯一一個從機器照片變成WebApp，所以檢索上不會直覺地想到是同一個，但其他WORK都一樣，讓我有點：？

CONTACT US的代表照會讓我覺得，原來這就是琥白團隊！（完了，其實不是）
建議改成意境照或是大家來拍新團體照！

**Comment by brookechiang** [comment]
<img width="1252" alt="截圖 2023-06-14 下午1 22 16" src="https://github.com/PowerCreationD/Kohaku/assets/111740253/ad378775-b0a7-45dc-8f30-4cba4c292e07">
<img width="1282" alt="截圖 2023-06-14 下午1 22 22" src="https://github.com/PowerCreationD/Kohaku/assets/111740253/7230c775-3514-426f-9fc5-4eb11e744815">
<img width="1061" alt="截圖 2023-06-14 下午1 22 45" src="https://github.com/PowerCreationD/Kohaku/assets/111740253/93f19d95-50ff-48d7-8f8a-3979f7773355">

**Comment by arien1014** [comment]
@Arthur118 
Work的MM換Homepage首圖
CONTACT US公司沒有代表照暫不換

**Comment by Arthur118** [comment]
@albert9052 @jozie-wang @arien1014 感覺在大南方前，我們可以將 contact us 的圖換成我們公司團拍的一張照片～

**Comment by jozie-wang** [comment]
@Arthur118 @arien1014 采蘋可嗎~

**Comment by arien1014** [comment]
@Arthur118 @jozie-wang @albert9052 
換好了放在figma～
<img width="793" alt="截圖 2023-08-22 下午4 53 49" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/385181f6-95af-43fa-bdc4-d78f3a29df5b">

**Comment by jozie-wang** [comment]
done
