### ISSUE TITLE
Homepage: 手機版的畫面，擠擠的

### ISSUE THREAD

**Issue by brookechiang** [PowerCreationD/Kohaku#46]
![S__38658052](https://github.com/PowerCreationD/Kohaku/assets/111740253/8785cf78-ff57-4c2a-b51e-948a9b629339)

切換畫面同一排有點擠（不容易按），底下文字呈現也有點窄
裝置：iPhone 13

**Comment by albert9052** [comment]
Duplicated of #13

**Comment by albert9052** [comment]
Duplicate of #13
