### ISSUE TITLE
Homepage : 手機版訊息呈現不完整，且無法直接點擊進入

### ISSUE THREAD

**Issue by brookechiang** [PowerCreationD/Kohaku#47]
![S__38658050](https://github.com/PowerCreationD/Kohaku/assets/111740253/f703b4cd-6aa8-4b92-ae9f-1b3db2cff38d)
看不完文字段落，也無法直接點擊進入該作品看到更多，閱讀會有點困擾，不知道該怎麼辦QQ

**Comment by albert9052** [comment]
@jozie-wang ( @arien1014 )
讓使用者能點擊圖片或是 title 進入該專案？

**Comment by jozie-wang** [comment]
@albert9052
我覺得兩個都可以放~

**Comment by jozie-wang** [comment]
closed
