### ISSUE TITLE
Homepage: contact us照片像素有點低

### ISSUE THREAD

**Issue by arien1014** [PowerCreationD/Kohaku#5]
希望contact的像素可以高一點點
<img width="1467" alt="截圖 2023-06-08 下午5 56 22" src="https://github.com/PowerCreationD/Kohaku/assets/48413041/0fc29cda-f6d4-4150-ab90-2fee8c426304">

**Comment by albert9052** [comment]
@arien1014 
改好了，如果看一下沒問題可以幫我把這個 issue 關掉唷，感謝！
