### ISSUE TITLE
Website: 進入 kohakustudio.co 出現 Chrome 瀏覽器警告

### ISSUE THREAD

**Issue by Arthur118** [PowerCreationD/Kohaku#57]
瀏覽器跳出警告，判斷我們為釣魚網站，假冒其他網站

![Screen Shot 2023-07-06 at 4 41 51 PM](https://github.com/PowerCreationD/Kohaku/assets/53463236/85ce516a-c327-4c73-9d05-7b9394464773)
![Screen Shot 2023-07-06 at 4 50 44 PM](https://github.com/PowerCreationD/Kohaku/assets/53463236/47c47c40-184a-47dd-990a-e08c4c45464f)

**Comment by Arthur118** [comment]
@jozie-wang @albert9052 我這邊初步判斷的原因是 kohakustudio.co 的 head 的 meta tag 中有填到 url 的部分應該都還是 kohakulab.com。將它替換為 kohakustudio.co 後應該就不會被判定為釣魚網站了。

**Comment by jozie-wang** [comment]
fixed
